import {useEffect,useMemo,useState} from "react";
import AppLayout from "../components/AppLayout"; import {supabase} from "../lib/supabase";
type Row={loan_number:number;expected_total:number;collected_total:number;outstanding_total:number;overdue_installments:number;next_due_date:string|null};
export default function AdminServicingDashboard(){const [rows,setRows]=useState<Row[]>([]);const [exceptions,setExceptions]=useState<any[]>([]);const [loading,setLoading]=useState(true);
async function load(){setLoading(true);const [a,b]=await Promise.all([supabase.from('admin_servicing_summary').select('*').order('loan_number'),supabase.from('financial_exceptions').select('*').eq('status','open').order('created_at',{ascending:false})]);setRows((a.data||[]) as Row[]);setExceptions(b.data||[]);setLoading(false)} useEffect(()=>{void load()},[]);
const totals=useMemo(()=>rows.reduce((x,r)=>({e:x.e+Number(r.expected_total||0),c:x.c+Number(r.collected_total||0),o:x.o+Number(r.outstanding_total||0),m:x.m+Number(r.overdue_installments||0)}),{e:0,c:0,o:0,m:0}),[rows]); const money=(n:number)=>n.toLocaleString(undefined,{style:'currency',currency:'USD'});
return <AppLayout><div className="mx-auto max-w-7xl p-6"><div className="flex items-center justify-between"><div><h1 className="text-3xl font-black">Loan Servicing & Reconciliation</h1><p className="text-slate-600">Expected, collected, outstanding, missed payments and processor exceptions.</p></div><button onClick={()=>void load()} className="rounded-xl bg-slate-900 px-4 py-2 font-bold text-white">Refresh</button></div>
<div className="mt-6 grid gap-4 md:grid-cols-5">{[['Expected',money(totals.e)],['Collected',money(totals.c)],['Outstanding',money(totals.o)],['Missed/Late',String(totals.m)],['Exceptions',String(exceptions.length)]].map(([a,b])=><div key={a} className="rounded-2xl border bg-white p-5"><p className="text-sm font-bold text-slate-500">{a}</p><p className="mt-2 text-2xl font-black">{b}</p></div>)}</div>
<div className="mt-6 overflow-x-auto rounded-2xl border bg-white"><table className="w-full text-left"><thead className="bg-slate-100"><tr>{['Loan #','Expected','Collected','Outstanding','Late/Missed','Next Due'].map(x=><th className="p-3" key={x}>{x}</th>)}</tr></thead><tbody>{rows.map(r=><tr className="border-t" key={r.loan_number}><td className="p-3 font-black">#{r.loan_number}</td><td className="p-3">{money(Number(r.expected_total))}</td><td className="p-3">{money(Number(r.collected_total))}</td><td className="p-3">{money(Number(r.outstanding_total))}</td><td className="p-3">{r.overdue_installments}</td><td className="p-3">{r.next_due_date||'—'}</td></tr>)}</tbody></table>{!loading&&rows.length===0&&<p className="p-6 text-slate-500">No servicing schedules yet.</p>}</div>
<div className="mt-6 rounded-2xl border bg-white p-5"><h2 className="text-xl font-black">Reconciliation Exceptions</h2>{exceptions.length===0?<p className="mt-3 text-emerald-700 font-bold">Reconciled — no open exceptions.</p>:<div className="mt-3 space-y-2">{exceptions.map(e=><div key={e.id} className="rounded-xl border border-amber-200 bg-amber-50 p-3"><b>{e.exception_type}</b> · Loan #{e.loan_number||'—'}<div className="text-sm">{e.source_reference||e.source||''}</div></div>)}</div>}</div></div></AppLayout>}
