import { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { supabase } from '../lib/supabase';
const money=(n:any)=>Number(n||0).toLocaleString(undefined,{style:'currency',currency:'USD'});
export default function SecondaryLoanDetails(){
 const {loanNumber}=useParams(); const [loan,setLoan]=useState<any>(null); const [schedule,setSchedule]=useState<any[]>([]); const [error,setError]=useState('');
 useEffect(()=>{(async()=>{if(!supabase)return; const [l,s]=await Promise.all([supabase.from('loan_applications').select('*').eq('loan_number',Number(loanNumber)).maybeSingle(),supabase.from('loan_payment_schedule').select('installment_number,due_date,expected_total,status,paid_at').eq('loan_number',Number(loanNumber)).order('installment_number')]); if(l.error)setError(l.error.message); setLoan(l.data); setSchedule(s.data||[]);})()},[loanNumber]);
 const paid=schedule.filter(x=>x.status==='paid'), onTime=paid.filter(x=>x.paid_at&&new Date(x.paid_at)<=new Date(`${x.due_date}T23:59:59`)), bad=schedule.filter(x=>x.status==='late'||x.status==='missed');
 return <section className="page" style={{maxWidth:1000,margin:'0 auto',padding:'32px 20px 72px'}}><Link to="/secondary-market">← Secondary Market</Link><p className="eyebrow" style={{marginTop:24}}>UNDERLYING LOAN</p><h1>Loan #{loanNumber}</h1>{error&&<div className="notice">{error}</div>}{loan&&<><div className="panel" style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(150px,1fr))',gap:12,padding:20,borderRadius:20}}><Stat l="Loan amount" v={money(loan.loan_amount)}/><Stat l="Status" v={loan.status||'—'}/><Stat l="Term" v={loan.repayment_term_months?`${loan.repayment_term_months} months`:'—'}/><Stat l="Property" v={loan.property_address||'On file'}/><Stat l="Land type" v={loan.land_type||'—'}/><Stat l="Acreage" v={loan.acreage?String(loan.acreage):'—'}/></div><h2 style={{marginTop:28}}>Payment performance</h2><div className="panel" style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(150px,1fr))',gap:12,padding:20,borderRadius:20}}><Stat l="Payments made" v={String(paid.length)}/><Stat l="Paid on time" v={String(onTime.length)}/><Stat l="Late / missed" v={String(bad.length)}/><Stat l="Scheduled payments" v={String(schedule.length)}/></div></>} {!loan&&!error&&<div className="panel">Loading loan record…</div>}</section>
}
function Stat({l,v}:{l:string,v:string}){return <div style={{padding:14,background:'rgba(255,255,255,.045)',borderRadius:14}}><div style={{fontSize:11,opacity:.6,textTransform:'uppercase'}}>{l}</div><strong>{v}</strong></div>}
