begin;

create table if not exists public.tax_profiles (
  id bigint generated by default as identity primary key,
  user_id uuid not null unique references auth.users(id) on delete cascade,
  legal_name text,
  business_name text,
  taxpayer_type text,
  tin_last4 text check (tin_last4 is null or tin_last4 ~ '^[0-9]{4}$'),
  mailing_address text,
  electronic_delivery_consent boolean not null default false,
  consented_at timestamptz,
  profile_status text not null default 'incomplete',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.tax_documents (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  recipient_role text not null check (recipient_role in ('borrower','investor')),
  tax_year integer not null check (tax_year between 2000 and 2200),
  form_type text not null,
  title text not null,
  status text not null default 'pending' check (status in ('pending','available','corrected','voided')),
  storage_path text,
  loan_application_id bigint references public.loan_applications(id) on delete set null,
  investment_id bigint,
  issued_at timestamptz,
  corrected_at timestamptz,
  created_by uuid references auth.users(id) on delete set null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.tax_download_history (
  id bigint generated by default as identity primary key,
  tax_document_id bigint not null references public.tax_documents(id) on delete cascade,
  user_id uuid not null default auth.uid(),
  download_source text,
  user_agent text,
  downloaded_at timestamptz not null default now()
);

create table if not exists public.tax_document_audit (
  id bigint generated by default as identity primary key,
  tax_document_id bigint references public.tax_documents(id) on delete cascade,
  actor_user_id uuid default auth.uid(),
  action text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists tax_documents_user_year_idx on public.tax_documents(user_id, tax_year desc);
create index if not exists tax_documents_status_idx on public.tax_documents(status);
create index if not exists tax_download_history_document_idx on public.tax_download_history(tax_document_id, downloaded_at desc);

insert into storage.buckets (id, name, public)
values ('tax-documents', 'tax-documents', false)
on conflict (id) do update set public = false;

alter table public.tax_profiles enable row level security;
alter table public.tax_documents enable row level security;
alter table public.tax_download_history enable row level security;
alter table public.tax_document_audit enable row level security;

create or replace function public.is_secured_landing_admin()
returns boolean language sql stable security definer set search_path = public
as $$ select exists(select 1 from public.admin_users where user_id = auth.uid()) $$;

drop policy if exists "Users view own tax profile" on public.tax_profiles;
create policy "Users view own tax profile" on public.tax_profiles for select to authenticated using (user_id = auth.uid() or public.is_secured_landing_admin());
drop policy if exists "Users update own tax profile" on public.tax_profiles;
create policy "Users update own tax profile" on public.tax_profiles for all to authenticated using (user_id = auth.uid() or public.is_secured_landing_admin()) with check (user_id = auth.uid() or public.is_secured_landing_admin());

drop policy if exists "Users view own tax documents" on public.tax_documents;
create policy "Users view own tax documents" on public.tax_documents for select to authenticated using (user_id = auth.uid() or public.is_secured_landing_admin());
drop policy if exists "Admins manage tax documents" on public.tax_documents;
create policy "Admins manage tax documents" on public.tax_documents for all to authenticated using (public.is_secured_landing_admin()) with check (public.is_secured_landing_admin());

drop policy if exists "Users log own tax downloads" on public.tax_download_history;
create policy "Users log own tax downloads" on public.tax_download_history for insert to authenticated with check (user_id = auth.uid() and exists(select 1 from public.tax_documents d where d.id = tax_document_id and (d.user_id = auth.uid() or public.is_secured_landing_admin())));
drop policy if exists "Users view own tax downloads" on public.tax_download_history;
create policy "Users view own tax downloads" on public.tax_download_history for select to authenticated using (user_id = auth.uid() or public.is_secured_landing_admin());

drop policy if exists "Admins view tax audit" on public.tax_document_audit;
create policy "Admins view tax audit" on public.tax_document_audit for all to authenticated using (public.is_secured_landing_admin()) with check (public.is_secured_landing_admin());

drop policy if exists "Users download own tax files" on storage.objects;
create policy "Users download own tax files" on storage.objects for select to authenticated using (bucket_id = 'tax-documents' and ((storage.foldername(name))[1] = auth.uid()::text or public.is_secured_landing_admin()));
drop policy if exists "Admins upload tax files" on storage.objects;
create policy "Admins upload tax files" on storage.objects for insert to authenticated with check (bucket_id = 'tax-documents' and public.is_secured_landing_admin());
drop policy if exists "Admins update tax files" on storage.objects;
create policy "Admins update tax files" on storage.objects for update to authenticated using (bucket_id = 'tax-documents' and public.is_secured_landing_admin()) with check (bucket_id = 'tax-documents' and public.is_secured_landing_admin());
drop policy if exists "Admins delete tax files" on storage.objects;
create policy "Admins delete tax files" on storage.objects for delete to authenticated using (bucket_id = 'tax-documents' and public.is_secured_landing_admin());

grant select, insert, update on public.tax_profiles to authenticated;
grant select, insert, update, delete on public.tax_documents to authenticated;
grant select, insert on public.tax_download_history to authenticated;
grant select, insert on public.tax_document_audit to authenticated;
grant usage, select on all sequences in schema public to authenticated;

notify pgrst, 'reload schema';
commit;
