-- SecuredLanding v3.0 Closing & Funding Foundation
-- Safe additive migration. It does not expose original borrower documents to investors.
begin;

alter table if exists public.loan_applications
  add column if not exists closing_status text default 'not_started',
  add column if not exists closing_started_at timestamptz,
  add column if not exists closing_completed_at timestamptz,
  add column if not exists borrower_signed_at timestamptz,
  add column if not exists final_verification_at timestamptz,
  add column if not exists disbursement_scheduled_at timestamptz,
  add column if not exists disbursed_at timestamptz;

alter table if exists public.loan_closings
  add column if not exists closing_status text default 'borrower_actions',
  add column if not exists funding_started_at timestamptz,
  add column if not exists funding_deadline timestamptz,
  add column if not exists closing_completed_at timestamptz,
  add column if not exists final_verification_status text default 'pending';

alter table if exists public.marketplace_loans
  add column if not exists funding_started_at timestamptz,
  add column if not exists funding_deadline timestamptz,
  add column if not exists investor_count integer not null default 0,
  add column if not exists recent_investment_at timestamptz,
  add column if not exists funding_status text not null default 'open';

alter table if exists public.generated_loan_documents
  add column if not exists visibility text not null default 'private',
  add column if not exists contains_sensitive_data boolean not null default true,
  add column if not exists redacted_storage_path text,
  add column if not exists approved_for_investors boolean not null default false,
  add column if not exists investor_approved_at timestamptz,
  add column if not exists investor_approved_by uuid references auth.users(id),
  add column if not exists signature_status text not null default 'ready_to_sign',
  add column if not exists signature_provider text,
  add column if not exists signature_envelope_id text,
  add column if not exists viewed_at timestamptz,
  add column if not exists signed_at timestamptz,
  add column if not exists signed_storage_path text;

create table if not exists public.document_access_log (
  id bigint generated by default as identity primary key,
  document_id bigint,
  loan_application_id bigint references public.loan_applications(id) on delete cascade,
  actor_user_id uuid references auth.users(id),
  action text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists document_access_log_loan_idx on public.document_access_log(loan_application_id, created_at desc);
create index if not exists marketplace_funding_deadline_idx on public.marketplace_loans(funding_deadline);

-- Start a 45-day window for already-open marketplace loans that have no deadline.
update public.marketplace_loans
set funding_started_at = coalesce(funding_started_at, now()),
    funding_deadline = coalesce(funding_deadline, now() + interval '45 days')
where lower(coalesce(status, 'open')) in ('open','approved','published','funding')
  and funding_deadline is null;

-- Privacy guard: investor-safe requires a distinct redacted copy.
do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'generated_docs_visibility_check') then
    alter table public.generated_loan_documents
      add constraint generated_docs_visibility_check
      check (visibility in ('private','investor_safe','public_summary'));
  end if;
  if not exists (select 1 from pg_constraint where conname = 'generated_docs_redacted_publication_check') then
    alter table public.generated_loan_documents
      add constraint generated_docs_redacted_publication_check
      check (approved_for_investors = false or (visibility = 'investor_safe' and redacted_storage_path is not null));
  end if;
end $$;

alter table public.document_access_log enable row level security;

drop policy if exists "Borrowers can view own document access" on public.document_access_log;
create policy "Borrowers can view own document access" on public.document_access_log
for select to authenticated using (
  exists (select 1 from public.loan_applications la where la.id = document_access_log.loan_application_id and la.user_id = auth.uid())
  or public.is_secured_landing_admin()
);

drop policy if exists "Admins can insert document access" on public.document_access_log;
create policy "Admins can insert document access" on public.document_access_log
for insert to authenticated with check (actor_user_id = auth.uid());

notify pgrst, 'reload schema';
commit;
