-- SecuredLanding v4.5.3 — Proof remote online notarization integration
-- Adds provider status/audit storage and distinct notarization + county-recording tasks.
-- Safe to rerun.

create table if not exists public.proof_notary_transactions (
  id bigint generated by default as identity primary key,
  loan_application_id bigint not null references public.loan_applications(id) on delete cascade,
  borrower_user_id uuid not null,
  provider text not null default 'proof',
  environment text not null default 'fairfax' check (environment in ('fairfax','production')),
  status text not null default 'not_started',
  eligibility_status text not null default 'not_checked',
  property_supported boolean,
  eligibility_response jsonb,
  proof_transaction_id text,
  proof_transaction_status text,
  proof_transaction_response jsonb,
  documents_uploaded integer not null default 0,
  uploaded_document_tracking_ids jsonb not null default '[]'::jsonb,
  placed_order_at timestamptz,
  notarized_at timestamptz,
  released_at timestamptz,
  last_webhook_event text,
  last_webhook_at timestamptz,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (loan_application_id),
  unique (proof_transaction_id)
);


alter table public.proof_notary_transactions
  add column if not exists uploaded_document_tracking_ids jsonb not null default '[]'::jsonb;

create index if not exists proof_notary_transactions_borrower_idx
  on public.proof_notary_transactions (borrower_user_id);

create table if not exists public.proof_webhook_events (
  id bigint generated by default as identity primary key,
  proof_transaction_id text not null,
  event_name text not null,
  occurred_at timestamptz,
  payload jsonb not null,
  received_at timestamptz not null default now(),
  unique (proof_transaction_id, event_name, occurred_at)
);

alter table public.proof_notary_transactions enable row level security;
alter table public.proof_webhook_events enable row level security;

drop policy if exists "Borrowers view own Proof closings" on public.proof_notary_transactions;
create policy "Borrowers view own Proof closings"
on public.proof_notary_transactions for select
using (borrower_user_id = auth.uid() or public.is_secured_landing_admin());

drop policy if exists "Admins manage Proof closings" on public.proof_notary_transactions;
create policy "Admins manage Proof closings"
on public.proof_notary_transactions for all
using (public.is_secured_landing_admin())
with check (public.is_secured_landing_admin());

drop policy if exists "Admins view Proof webhook events" on public.proof_webhook_events;
create policy "Admins view Proof webhook events"
on public.proof_webhook_events for select
using (public.is_secured_landing_admin());

-- Existing closings: preserve completed work, insert the two new independent steps.
insert into public.closing_tasks (loan_closing_id, loan_application_id, task_key, title, status, sort_order)
select lc.id, lc.loan_application_id, 'online_notary', 'Complete remote online notarization', 'pending', 6
from public.loan_closings lc
where not exists (
  select 1 from public.closing_tasks ct
  where ct.loan_application_id = lc.loan_application_id and ct.task_key = 'online_notary'
)
on conflict do nothing;

insert into public.closing_tasks (loan_closing_id, loan_application_id, task_key, title, status, sort_order)
select lc.id, lc.loan_application_id, 'county_recording', 'Record security instrument with county', 'pending', 7
from public.loan_closings lc
where not exists (
  select 1 from public.closing_tasks ct
  where ct.loan_application_id = lc.loan_application_id and ct.task_key = 'county_recording'
)
on conflict do nothing;

update public.closing_tasks set sort_order = 8 where task_key = 'investor_funding';
update public.closing_tasks set sort_order = 9 where task_key = 'disbursement';

comment on table public.proof_notary_transactions is
'Proof RON/eClosing provider state. Notarization completion is intentionally separate from county recording.';
