-- SecuredLanding v2.7
-- Secure document visibility, borrower signing center, audit log and 45-day funding window.

begin;

-- Uploaded underwriting documents: originals remain private by default.
alter table public.loan_documents
  add column if not exists visibility text not null default 'private',
  add column if not exists contains_sensitive_data boolean not null default true,
  add column if not exists redacted_storage_path text,
  add column if not exists approved_for_investors boolean not null default false,
  add column if not exists investor_approved_at timestamptz,
  add column if not exists investor_approved_by uuid references auth.users(id),
  add column if not exists updated_at timestamptz not null default now();

alter table public.loan_documents drop constraint if exists loan_documents_visibility_check;
alter table public.loan_documents add constraint loan_documents_visibility_check
  check (visibility in ('private', 'investor_safe', 'public_summary'));

-- Generated borrower signing documents always stay private.
alter table public.generated_loan_documents
  add column if not exists visibility text not null default 'private',
  add column if not exists contains_sensitive_data boolean not null default true,
  add column if not exists signature_status text not null default 'ready_to_sign',
  add column if not exists signed_storage_path text,
  add column if not exists viewed_at timestamptz,
  add column if not exists submitted_at timestamptz,
  add column if not exists accepted_at timestamptz,
  add column if not exists correction_notes text;

alter table public.generated_loan_documents drop constraint if exists generated_loan_documents_signature_status_check;
alter table public.generated_loan_documents add constraint generated_loan_documents_signature_status_check
  check (signature_status in ('ready_to_sign','viewed','signed','submitted','accepted','needs_correction'));

-- 45-day funding timeline.
alter table public.loan_applications
  add column if not exists approved_at timestamptz,
  add column if not exists funding_started_at timestamptz,
  add column if not exists funding_deadline timestamptz,
  add column if not exists funding_window_days integer not null default 45,
  add column if not exists funding_status text not null default 'not_started';

alter table public.loan_applications drop constraint if exists loan_applications_funding_status_check;
alter table public.loan_applications add constraint loan_applications_funding_status_check
  check (funding_status in ('not_started','open','paused','fully_funded','expired','cancelled','closing','deposited'));

alter table public.marketplace_loans
  add column if not exists funding_started_at timestamptz,
  add column if not exists funding_deadline timestamptz,
  add column if not exists funding_window_days integer not null default 45,
  add column if not exists funding_status text not null default 'open',
  add column if not exists minimum_investment numeric not null default 100,
  add column if not exists investor_count integer not null default 0,
  add column if not exists last_funding_activity_at timestamptz;

-- Audit trail for access and visibility changes.
create table if not exists public.document_access_log (
  id bigint generated by default as identity primary key,
  loan_document_id bigint,
  generated_document_id bigint,
  loan_application_id bigint,
  actor_user_id uuid references auth.users(id),
  action text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  check (action in ('view','download','upload','approve_underwriting','publish_investor_copy','change_visibility','sign','submit_signature','accept_signature','request_correction'))
);

create index if not exists loan_documents_visibility_idx on public.loan_documents(visibility, approved_for_investors);
create index if not exists generated_documents_borrower_signature_idx on public.generated_loan_documents(borrower_user_id, signature_status);
create index if not exists marketplace_funding_deadline_idx on public.marketplace_loans(funding_status, funding_deadline);
create index if not exists document_access_log_application_idx on public.document_access_log(loan_application_id, created_at desc);

alter table public.document_access_log enable row level security;

drop policy if exists "Borrowers can read own document access log" on public.document_access_log;
create policy "Borrowers can read own document access log"
on public.document_access_log for select to authenticated
using (
  exists (
    select 1 from public.loan_applications la
    where la.id = document_access_log.loan_application_id
      and la.user_id = auth.uid()
  )
);

drop policy if exists "Admins can manage document access log" on public.document_access_log;
create policy "Admins can manage document access log"
on public.document_access_log for all to authenticated
using (exists (select 1 from public.admin_users au where au.user_id = auth.uid()))
with check (exists (select 1 from public.admin_users au where au.user_id = auth.uid()));

-- Investors may only read explicitly approved redacted/investor-safe document metadata.
drop policy if exists "Investors can read approved safe loan documents" on public.loan_documents;
create policy "Investors can read approved safe loan documents"
on public.loan_documents for select to authenticated
using (
  approved_for_investors = true
  and visibility in ('investor_safe','public_summary')
  and redacted_storage_path is not null
);

-- Originals remain accessible to owner and admins through existing policies.
-- This policy ensures borrower-generated signing documents remain borrower/admin only.
drop policy if exists "Borrowers can read own generated signing documents" on public.generated_loan_documents;
create policy "Borrowers can read own generated signing documents"
on public.generated_loan_documents for select to authenticated
using (borrower_user_id = auth.uid());

drop policy if exists "Borrowers can update own generated signing documents" on public.generated_loan_documents;
create policy "Borrowers can update own generated signing documents"
on public.generated_loan_documents for update to authenticated
using (borrower_user_id = auth.uid())
with check (borrower_user_id = auth.uid() and visibility = 'private');

-- Keep existing records safe.
update public.loan_documents
set visibility = 'private', contains_sensitive_data = true, approved_for_investors = false
where visibility is null;

update public.generated_loan_documents
set visibility = 'private', contains_sensitive_data = true
where visibility is null;

notify pgrst, 'reload schema';
commit;
