begin;

create table if not exists public.counteroffer_acceptance_audit (
  id bigint generated by default as identity primary key,
  counteroffer_id bigint not null references public.loan_counteroffers(id) on delete cascade,
  loan_application_id bigint not null references public.loan_applications(id) on delete cascade,
  borrower_user_id uuid not null,
  response text not null check (response in ('accepted', 'declined')),
  agreement_version text not null default 'counteroffer-v1.0',
  user_agent text,
  responded_at timestamptz not null default now(),
  response_metadata jsonb not null default '{}'::jsonb
);

create unique index if not exists counteroffer_acceptance_audit_offer_unique
  on public.counteroffer_acceptance_audit(counteroffer_id);

alter table public.counteroffer_acceptance_audit enable row level security;

drop policy if exists "Borrowers view own counteroffer audit" on public.counteroffer_acceptance_audit;
create policy "Borrowers view own counteroffer audit"
  on public.counteroffer_acceptance_audit for select to authenticated
  using (borrower_user_id = auth.uid());

drop policy if exists "Admins view counteroffer audit" on public.counteroffer_acceptance_audit;
create policy "Admins view counteroffer audit"
  on public.counteroffer_acceptance_audit for select to authenticated
  using (exists (select 1 from public.admin_users a where a.user_id = auth.uid()));

create or replace function public.respond_to_loan_counteroffer(
  p_counteroffer_id bigint,
  p_accept boolean,
  p_user_agent text default null,
  p_agreement_version text default 'counteroffer-v1.0'
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_offer public.loan_counteroffers%rowtype;
  v_now timestamptz := now();
  v_status text;
  v_message text;
begin
  if v_user_id is null then raise exception 'Authentication required'; end if;

  select * into v_offer
  from public.loan_counteroffers
  where id = p_counteroffer_id
  for update;

  if not found then raise exception 'Counteroffer not found'; end if;
  if v_offer.borrower_user_id is distinct from v_user_id then
    raise exception 'You are not authorized to respond to this counteroffer';
  end if;
  if v_offer.status <> 'pending' then
    raise exception 'This counteroffer has already been answered';
  end if;

  v_status := case when p_accept then 'accepted' else 'declined' end;
  v_message := case when p_accept
    then 'The borrower accepted the revised loan offer of ' || to_char(v_offer.proposed_loan_amount, 'FM$999,999,999,990.00')
    else 'The borrower declined the revised loan offer of ' || to_char(v_offer.proposed_loan_amount, 'FM$999,999,999,990.00')
  end;

  update public.loan_counteroffers set
    status = v_status,
    accepted_at = case when p_accept then v_now else null end,
    declined_at = case when p_accept then null else v_now end,
    updated_at = v_now
  where id = v_offer.id;

  update public.loan_applications set
    approved_loan_amount = case when p_accept then v_offer.proposed_loan_amount else approved_loan_amount end,
    loan_amount = case when p_accept then v_offer.proposed_loan_amount else loan_amount end,
    amount_remaining = case when p_accept then greatest(v_offer.proposed_loan_amount - coalesce(amount_funded, 0), 0) else amount_remaining end,
    counteroffer_status = v_status,
    counteroffer_responded_at = v_now,
    status = case when p_accept then 'Counteroffer Accepted' else 'Counteroffer Declined' end,
    published_to_marketplace = false
  where id = v_offer.loan_application_id and user_id = v_user_id;

  if not found then raise exception 'Matching borrower loan application not found'; end if;

  insert into public.counteroffer_acceptance_audit (
    counteroffer_id, loan_application_id, borrower_user_id, response,
    agreement_version, user_agent, responded_at, response_metadata
  ) values (
    v_offer.id, v_offer.loan_application_id, v_user_id, v_status,
    coalesce(nullif(trim(p_agreement_version), ''), 'counteroffer-v1.0'),
    p_user_agent, v_now,
    jsonb_build_object(
      'original_amount', v_offer.original_loan_amount,
      'proposed_amount', v_offer.proposed_loan_amount,
      'interest_rate', v_offer.borrower_interest_rate,
      'term_months', v_offer.repayment_term_months,
      'resulting_ltv_percent', v_offer.resulting_ltv_percent
    )
  );

  insert into public.messages (
    loan_application_id, sender_user_id, recipient_user_id,
    sender_id, recipient_id, sender_role, message_type,
    subject, body, counteroffer_id, metadata, read
  ) values (
    v_offer.loan_application_id, v_user_id, v_offer.created_by,
    v_user_id, v_offer.created_by, 'borrower', 'counteroffer_response',
    case when p_accept then 'Revised loan offer accepted' else 'Revised loan offer declined' end,
    v_message, v_offer.id,
    jsonb_build_object('response', v_status, 'responded_at', v_now), false
  );

  return jsonb_build_object(
    'success', true,
    'counteroffer_id', v_offer.id,
    'loan_application_id', v_offer.loan_application_id,
    'status', v_status,
    'responded_at', v_now
  );
end;
$$;

revoke all on function public.respond_to_loan_counteroffer(bigint, boolean, text, text) from public;
grant execute on function public.respond_to_loan_counteroffer(bigint, boolean, text, text) to authenticated;

notify pgrst, 'reload schema';
commit;
