-- SecuredLanding v2.5.0 MASTER MIGRATION
-- Safe to run repeatedly. Aligns the production database with the v2.5.0 application.
-- Existing public.loan_applications.id is expected to be bigint.

create extension if not exists pgcrypto;

-- Shared admin helper
create or replace function public.is_secured_landing_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.admin_users where user_id = auth.uid()
  );
$$;

-- Borrower video workflow
alter table public.loan_applications
  add column if not exists borrower_video_path text,
  add column if not exists borrower_video_status text default 'not_submitted',
  add column if not exists borrower_video_admin_notes text,
  add column if not exists borrower_video_reviewed_at timestamptz,
  add column if not exists borrower_video_reviewed_by uuid references auth.users(id),
  add column if not exists published_to_marketplace boolean not null default false,
  add column if not exists amount_funded numeric(14,2) not null default 0,
  add column if not exists amount_remaining numeric(14,2),
  add column if not exists borrower_interest_rate numeric(7,3),
  add column if not exists investor_interest_rate numeric(7,3),
  add column if not exists company_spread_rate numeric(7,3),
  add column if not exists risk_score text,
  add column if not exists underwriter_notes text;

alter table public.loan_applications
  drop constraint if exists loan_applications_borrower_video_status_check;
alter table public.loan_applications
  add constraint loan_applications_borrower_video_status_check
  check (borrower_video_status in ('not_submitted','under_review','approved','more_information','rejected'));

-- Investor marketplace table and all columns consumed by the UI
create table if not exists public.marketplace_loans (
  id bigint generated by default as identity primary key,
  loan_application_id bigint not null unique references public.loan_applications(id) on delete cascade,
  loan_number bigint,
  business_name text,
  borrower_name text,
  apn text,
  state text,
  acreage numeric(14,3),
  land_value numeric(14,2) not null default 0,
  loan_amount numeric(14,2) not null default 0,
  borrower_interest_rate numeric(7,3),
  investor_interest_rate numeric(7,3),
  company_spread_rate numeric(7,3),
  repayment_term_months integer not null default 36,
  risk_score text,
  funding_goal numeric(14,2) not null default 0,
  amount_funded numeric(14,2) not null default 0,
  amount_remaining numeric(14,2) not null default 0,
  borrower_video_path text,
  borrower_video_status text not null default 'not_submitted',
  property_photos jsonb not null default '[]'::jsonb,
  status text not null default 'Open',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.marketplace_loans
  add column if not exists borrower_video_path text,
  add column if not exists borrower_video_status text default 'not_submitted',
  add column if not exists property_photos jsonb default '[]'::jsonb,
  add column if not exists updated_at timestamptz not null default now();

create index if not exists marketplace_loans_status_idx on public.marketplace_loans(status);
create index if not exists marketplace_loans_application_idx on public.marketplace_loans(loan_application_id);

-- Generated loan documents. Compatibility columns are retained so old and new code can coexist.
create table if not exists public.generated_loan_documents (
  id uuid primary key default gen_random_uuid(),
  loan_application_id bigint not null references public.loan_applications(id) on delete cascade,
  borrower_user_id uuid references auth.users(id) on delete cascade,
  borrower_id uuid references auth.users(id) on delete cascade,
  document_type text not null,
  document_name text,
  title text,
  storage_path text,
  status text not null default 'ready_for_review',
  terms_snapshot jsonb not null default '{}'::jsonb,
  generated_at timestamptz not null default now(),
  sent_at timestamptz,
  acknowledged_at timestamptz,
  signed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.generated_loan_documents
  add column if not exists borrower_user_id uuid references auth.users(id),
  add column if not exists borrower_id uuid references auth.users(id),
  add column if not exists document_name text,
  add column if not exists title text,
  add column if not exists storage_path text,
  add column if not exists terms_snapshot jsonb default '{}'::jsonb,
  add column if not exists generated_at timestamptz not null default now(),
  add column if not exists sent_at timestamptz,
  add column if not exists acknowledged_at timestamptz,
  add column if not exists signed_at timestamptz,
  add column if not exists updated_at timestamptz not null default now();

update public.generated_loan_documents
set borrower_user_id = coalesce(borrower_user_id, borrower_id)
where borrower_user_id is null;

update public.generated_loan_documents
set title = coalesce(title, document_name, initcap(replace(document_type, '_', ' '))),
    document_name = coalesce(document_name, title, initcap(replace(document_type, '_', ' ')))
where title is null or document_name is null;

create unique index if not exists generated_loan_documents_loan_type_uidx
  on public.generated_loan_documents(loan_application_id, document_type);
create index if not exists generated_loan_documents_borrower_user_idx
  on public.generated_loan_documents(borrower_user_id, loan_application_id);

-- Closing center
create table if not exists public.loan_closings (
  id uuid primary key default gen_random_uuid(),
  loan_application_id bigint not null unique references public.loan_applications(id) on delete cascade,
  borrower_user_id uuid references auth.users(id) on delete cascade,
  stage text not null default 'borrower_actions',
  progress_percent integer not null default 12 check (progress_percent between 0 and 100),
  approved_loan_amount numeric(14,2) not null default 0,
  borrower_interest_rate numeric(7,3) not null default 0,
  investor_interest_rate numeric(7,3) not null default 0,
  repayment_term_months integer not null default 36,
  monthly_payment numeric(14,2),
  terms_locked_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.closing_tasks (
  id uuid primary key default gen_random_uuid(),
  loan_closing_id uuid not null references public.loan_closings(id) on delete cascade,
  loan_application_id bigint not null references public.loan_applications(id) on delete cascade,
  task_key text not null,
  title text not null,
  status text not null default 'pending',
  sort_order integer not null default 0,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  unique(loan_application_id, task_key)
);

create table if not exists public.borrower_notifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  loan_application_id bigint references public.loan_applications(id) on delete cascade,
  title text not null,
  message text not null,
  notification_type text not null default 'loan_update',
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.loan_timeline_events (
  id uuid primary key default gen_random_uuid(),
  loan_application_id bigint not null references public.loan_applications(id) on delete cascade,
  event_key text not null,
  title text not null,
  description text,
  actor_user_id uuid references auth.users(id),
  created_at timestamptz not null default now()
);

-- Row level security
alter table public.marketplace_loans enable row level security;
alter table public.generated_loan_documents enable row level security;
alter table public.loan_closings enable row level security;
alter table public.closing_tasks enable row level security;
alter table public.borrower_notifications enable row level security;
alter table public.loan_timeline_events enable row level security;

drop policy if exists "Authenticated users view open marketplace loans" on public.marketplace_loans;
create policy "Authenticated users view open marketplace loans"
on public.marketplace_loans for select to authenticated
using (status in ('Open','Funded') or public.is_secured_landing_admin());

drop policy if exists "Admins manage marketplace loans" on public.marketplace_loans;
create policy "Admins manage marketplace loans"
on public.marketplace_loans for all to authenticated
using (public.is_secured_landing_admin())
with check (public.is_secured_landing_admin());

drop policy if exists "Borrowers view own generated documents" on public.generated_loan_documents;
drop policy if exists "Borrowers can view their generated documents" on public.generated_loan_documents;
create policy "Borrowers view own generated documents"
on public.generated_loan_documents for select to authenticated
using (borrower_user_id = auth.uid() or public.is_secured_landing_admin());

drop policy if exists "Borrowers acknowledge own generated documents" on public.generated_loan_documents;
create policy "Borrowers acknowledge own generated documents"
on public.generated_loan_documents for update to authenticated
using (borrower_user_id = auth.uid() or public.is_secured_landing_admin())
with check (borrower_user_id = auth.uid() or public.is_secured_landing_admin());

drop policy if exists "Admins manage generated documents" on public.generated_loan_documents;
drop policy if exists "Admins can manage generated loan documents" on public.generated_loan_documents;
create policy "Admins manage generated documents"
on public.generated_loan_documents for all to authenticated
using (public.is_secured_landing_admin())
with check (public.is_secured_landing_admin());

-- Force PostgREST to reload the schema immediately.
notify pgrst, 'reload schema';
