-- SecuredLanding v2.8.1 - Investor-only 7-day cancellation/refund patch
-- Run in Supabase SQL Editor.
-- Designed around the confirmed investments schema:
-- id bigint, loan_id bigint, investor_id uuid, amount numeric, created_at timestamptz,
-- investor_interest_rate numeric, borrower_interest_rate numeric, company_spread_rate numeric,
-- term_months integer, status text, refund_policy_enabled boolean, refund_period_days integer,
-- refund_deadline timestamptz, refund_requested_at timestamptz, refunded_at timestamptz,
-- current_owner_id uuid, original_investor_id uuid, transfer_locked boolean, etc.

begin;

-- Ensure required refund columns exist without renaming the confirmed schema.
alter table public.investments
  add column if not exists refund_policy_enabled boolean not null default true,
  add column if not exists refund_period_days integer not null default 7,
  add column if not exists refund_deadline timestamptz,
  add column if not exists refund_requested_at timestamptz,
  add column if not exists refunded_at timestamptz,
  add column if not exists updated_at timestamptz default now();

-- Backfill deadlines from ORIGINAL investment time; never grant old investments a fresh 7 days.
update public.investments
set refund_deadline = created_at + (coalesce(refund_period_days, 7) * interval '1 day')
where refund_policy_enabled = true
  and refund_deadline is null
  and refunded_at is null;

create or replace function public.set_investment_refund_deadline()
returns trigger
language plpgsql
as $$
begin
  if new.refund_policy_enabled = true then
    new.refund_period_days := coalesce(new.refund_period_days, 7);
    if new.refund_deadline is null then
      new.refund_deadline :=
        coalesce(new.created_at, now()) +
        (new.refund_period_days * interval '1 day');
    end if;
  else
    new.refund_deadline := null;
  end if;
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists trg_set_investment_refund_deadline on public.investments;
create trigger trg_set_investment_refund_deadline
before insert or update of refund_policy_enabled, refund_period_days
on public.investments
for each row execute function public.set_investment_refund_deadline();

-- Audit table is intentionally independent of borrower notifications.
create table if not exists public.investment_refund_audit (
  id bigint generated by default as identity primary key,
  investment_id bigint not null references public.investments(id) on delete restrict,
  investor_id uuid not null,
  loan_id bigint,
  amount numeric(14,2) not null,
  action text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.investment_refund_audit enable row level security;

drop policy if exists "Investors view own refund audit" on public.investment_refund_audit;
create policy "Investors view own refund audit"
on public.investment_refund_audit for select to authenticated
using (investor_id = auth.uid());

-- Optional investor notification table used by this patch.
create table if not exists public.investor_notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  investment_id bigint references public.investments(id) on delete set null,
  title text not null,
  message text not null,
  notification_type text not null default 'investment_update',
  read_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.investor_notifications enable row level security;
drop policy if exists "Investors view own notifications" on public.investor_notifications;
create policy "Investors view own notifications"
on public.investor_notifications for select to authenticated
using (user_id = auth.uid());

-- Returns an eligible investment to the investor's wallet atomically.
-- The function discovers common wallet balance column names so it can work with
-- available_balance, balance, or available_cash without hard-coding the wrong one.
create or replace function public.cancel_investment_with_refund(p_investment_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_inv public.investments%rowtype;
  v_wallet_balance_col text;
  v_wallet_user_col text;
  v_wallet_id bigint;
  v_marketplace_id_col text;
  v_marketplace_row_id bigint;
begin
  if v_uid is null then
    raise exception 'Authentication required';
  end if;

  select *
  into v_inv
  from public.investments
  where id = p_investment_id
  for update;

  if not found then
    raise exception 'Investment not found';
  end if;

  if coalesce(v_inv.current_owner_id, v_inv.investor_id) <> v_uid then
    raise exception 'You do not own this investment';
  end if;

  if v_inv.refund_policy_enabled is distinct from true then
    raise exception 'This investment is not eligible for cancellation';
  end if;

  if v_inv.refund_deadline is null or now() > v_inv.refund_deadline then
    raise exception 'The 7-day cancellation period has expired';
  end if;

  if v_inv.refunded_at is not null or lower(coalesce(v_inv.status,'')) in
     ('refunded','cancelled','canceled','settled','processing') then
    raise exception 'This investment cannot be refunded in its current status';
  end if;

  -- Lock the investment against transfer while processing.
  update public.investments
  set refund_requested_at = coalesce(refund_requested_at, now()),
      status = 'processing',
      transfer_locked = true,
      updated_at = now()
  where id = v_inv.id;

  -- Detect investor_wallets user key.
  select c.column_name
  into v_wallet_user_col
  from information_schema.columns c
  where c.table_schema='public' and c.table_name='investor_wallets'
    and c.column_name in ('user_id','investor_id')
  order by case c.column_name when 'user_id' then 1 else 2 end
  limit 1;

  select c.column_name
  into v_wallet_balance_col
  from information_schema.columns c
  where c.table_schema='public' and c.table_name='investor_wallets'
    and c.column_name in ('available_balance','available_cash','balance')
  order by case c.column_name
    when 'available_balance' then 1
    when 'available_cash' then 2
    else 3 end
  limit 1;

  if v_wallet_user_col is null or v_wallet_balance_col is null then
    raise exception 'investor_wallets balance/user column not recognized';
  end if;

  -- Lock existing wallet row if present.
  execute format(
    'select id from public.investor_wallets where %I = $1 for update',
    v_wallet_user_col
  ) into v_wallet_id using v_uid;

  if v_wallet_id is null then
    raise exception 'Investor wallet not found';
  end if;

  execute format(
    'update public.investor_wallets set %I = coalesce(%I,0) + $1 where id = $2',
    v_wallet_balance_col, v_wallet_balance_col
  ) using v_inv.amount, v_wallet_id;

  -- Reverse funding totals on marketplace_loans when loan_id matches either id or loan_number.
  if to_regclass('public.marketplace_loans') is not null then
    if exists (
      select 1 from information_schema.columns
      where table_schema='public' and table_name='marketplace_loans' and column_name='loan_number'
    ) then
      update public.marketplace_loans
      set amount_funded = greatest(coalesce(amount_funded,0) - v_inv.amount, 0),
          amount_remaining = least(coalesce(funding_goal, loan_amount, 0),
                                   coalesce(amount_remaining,0) + v_inv.amount),
          status = 'Open',
          updated_at = now()
      where loan_number = v_inv.loan_id;
    end if;

    -- Legacy rows may have marketplace_loans.id = investments.loan_id.
    update public.marketplace_loans
    set amount_funded = greatest(coalesce(amount_funded,0) - v_inv.amount, 0),
        amount_remaining = least(coalesce(funding_goal, loan_amount, 0),
                                 coalesce(amount_remaining,0) + v_inv.amount),
        status = 'Open',
        updated_at = now()
    where id = v_inv.loan_id
      and not exists (
        select 1 from public.marketplace_loans ml2
        where ml2.loan_number = v_inv.loan_id
      );
  end if;

  -- Reverse canonical loan_applications totals if loan_number matches.
  if to_regclass('public.loan_applications') is not null then
    update public.loan_applications
    set amount_funded = greatest(coalesce(amount_funded,0) - v_inv.amount, 0),
        amount_remaining = least(coalesce(loan_amount,0),
                                 coalesce(amount_remaining,0) + v_inv.amount)
    where loan_number = v_inv.loan_id;
  end if;

  update public.investments
  set status = 'refunded',
      refunded_at = now(),
      transfer_locked = true,
      updated_at = now()
  where id = v_inv.id;

  insert into public.investment_refund_audit
    (investment_id, investor_id, loan_id, amount, action, details)
  values
    (v_inv.id, v_uid, v_inv.loan_id, v_inv.amount, 'refund_completed',
     jsonb_build_object('refund_deadline', v_inv.refund_deadline,
                        'returned_to_wallet', true));

  insert into public.investor_notifications
    (user_id, investment_id, title, message, notification_type)
  values
    (v_uid, v_inv.id, 'Investment cancellation completed',
     'Your investment cancellation was completed and the funds were returned to your available wallet cash.',
     'investment_refund');

  return jsonb_build_object(
    'ok', true,
    'investment_id', v_inv.id,
    'amount_refunded', v_inv.amount,
    'status', 'refunded'
  );
exception
  when others then
    -- PostgreSQL rolls back every change in this function on error.
    raise;
end;
$$;

revoke all on function public.cancel_investment_with_refund(bigint) from public;
grant execute on function public.cancel_investment_with_refund(bigint) to authenticated;

commit;

-- Verification:
-- select id, loan_id, amount, status, refund_policy_enabled, refund_period_days,
--        refund_deadline, refund_requested_at, refunded_at
-- from public.investments
-- order by created_at desc;
